export const projectUiCopy = {
  ko: {
    sectionTitle: "Core Projects",
    sectionIntro:
      "AI 코딩 에이전트로 만들고, 재현 테스트·독립 리뷰·전후 실측으로 검증한 개발 프로젝트를 먼저 보여 드립니다. 코드를 AI가 쓴 부분과 제가 지시·검증한 부분을 나눠 적었습니다.",
    coreKicker: "Development evidence",
    coreTitle: "대표 프로젝트 3",
    coreIntro:
      "Ops Sentinel, 장보고, RE:RUN — 문제정의, 역할, 기술 선택, 트러블슈팅(재현 → 원인 → 수정 → 전후 실측), 한계 순서로 정리했습니다.",
    supportingKicker: "Supporting / Hackathon",
    supportingTitle: "보조 프로젝트 및 해커톤",
    supportingIntro:
      "도메인 확장성, 빠른 실행력, 추가 아이디어를 보여주는 프로젝트는 하단 아카이브로 분리합니다.",
    problemDefinition: "한 줄 문제정의",
    coreContribution: "핵심 기여",
    techStack: "사용 기술",
    resultLearning: "결과 / 배운 점",
    submissionFormat: "SSAFY 제출 구조",
    overview: "프로젝트 개요",
    myRole: "수행 역할",
    solutionProcess: "해결 과정",
    interviewHooks: "면접 질문 포인트",
    viewDetails: "상세 보기",
    backToProjects: "프로젝트 목록으로 돌아가기",
    period: "기간",
    team: "팀 구성",
    role: "역할",
    links: "링크",
    highlights: "핵심 포인트",
    screens: "서비스 화면",
    themes: "키워드",
    challenge: "다룬 문제",
    insight: "구조적 인사이트",
    solution: "경험 설계 + 시스템 구조",
    artifacts: "추가 예정 자료",
    artifactEmpty:
      "와이어프레임, 화면 이미지, 코드 링크, 발표 자료를 프로젝트별로 순차적으로 정리할 예정입니다.",
    github: "GitHub",
    demo: "서비스 링크",
    docs: "문서 자료",
    video: "데모 영상",
    teamGithub: "팀 레포 (내 커밋)",
    fixPr: "수정 PR",
    linksPending: "링크 정리 중",
    statusLabels: {
      planning: "Planning",
      in_progress: "In Progress",
      completed: "Completed",
      archive_preparing: "Archive Prep",
    },
  },
  en: {
    sectionTitle: "Core Projects",
    sectionIntro:
      "Development projects built with AI coding agents and verified with reproduction tests, independent review, and before/after measurements come first. What the AI wrote and what I directed and verified are stated separately.",
    coreKicker: "Development evidence",
    coreTitle: "Core 3 Projects",
    coreIntro:
      "Ops Sentinel, JangBogo, and RE:RUN — organized as problem, role, technical choices, troubleshooting (reproduce → cause → fix → before/after), and limits.",
    supportingKicker: "Supporting / Hackathon",
    supportingTitle: "Supporting Projects & Hackathons",
    supportingIntro:
      "Additional projects are separated as archive cases that show domain expansion, rapid execution, and supporting ideas.",
    problemDefinition: "Problem definition",
    coreContribution: "Key contribution",
    techStack: "Tech stack",
    resultLearning: "Result / learning",
    submissionFormat: "SSAFY Portfolio Format",
    overview: "Project overview",
    myRole: "My role",
    solutionProcess: "Solution process",
    interviewHooks: "Interview hooks",
    viewDetails: "View details",
    backToProjects: "Back to project archive",
    period: "Period",
    team: "Team",
    role: "Role",
    links: "Links",
    highlights: "Highlights",
    screens: "Product Screens",
    themes: "Themes",
    challenge: "Challenge",
    insight: "Structural Insight",
    solution: "Experience + System Design",
    artifacts: "Planned archive assets",
    artifactEmpty:
      "Wireframes, UI captures, code links, and supporting documents will be attached as each project archive is documented.",
    github: "GitHub",
    demo: "Live link",
    docs: "Docs",
    video: "Demo video",
    teamGithub: "Team repo (my commits)",
    fixPr: "Fix PR",
    linksPending: "Links in preparation",
    statusLabels: {
      planning: "Planning",
      in_progress: "In Progress",
      completed: "Completed",
      archive_preparing: "Archive Prep",
    },
  },
};
